### ISSUE TITLE
MLJ model registry not catching new linear model

### ISSUE THREAD

**Issue by ablaom** [Evovest/EvoTrees.jl#165]
@jeremiedb It seems the new model does not have `MLJModelInterface.Model` as a supertype:

```julia
using MLJModels
using EvoTrees
julia> ms = MLJModels.finaltypes(MLJModels.Model);

julia> filter(ms) do m
           Base.parentmodule(m) == EvoTrees
       end
4-element Vector{Type}:
 EvoTreeRegressor
 EvoTreeClassifier
 EvoTreeCount
 EvoTreeGaussian
```

**Comment by jeremiedb** [comment]
Could you clarify whether there's an expected link between the new linear model and EvoTrees.jl? 
Although their APIs are mostly consistent, I'm treating linear models in EvoLinear.jl (https://github.com/jeremiedb/EvoLinear.jl) as completely independent to EvoTrees.jl. This is why I opened https://github.com/JuliaAI/MLJModels.jl/issues/481. 

By doing the following, I get the desired `EvoLinearRegressor`, so I'm not clear whether there's a problematic behavior:
```julia
using EvoLinear
ms = MLJModels.finaltypes(MLJModels.Model);
filter(ms) do m
  Base.parentmodule(m) == EvoLinear
end
  1-element Vector{Type}:
   EvoLinearRegressor
```

Let me know if I misunderstand the issue here.

**Comment by ablaom** [comment]
My bad 😳 . I hadn't realised these were supplied by a different package!
