### ISSUE TITLE
Plot loss curve history for train and eval data set

### ISSUE THREAD

**Issue by Moelf** [Evovest/EvoTrees.jl#178]
is the way to go "fit" for 1 round manually ?....

**Comment by jeremiedb** [comment]
Right now there's no tracking of the eval metrics throughout the iterations that is in place. 
I was actually thinking integrating them within the `info` element of a model that was introduced with v0.12. 
Given current parametrization, it would only track the eval metrics associated with eval data, if specified (not both train & eval, or any arbitrary selection of datasets).  
Otherwise, as of now, I think MLJ would be the most straightforward way to get those curves. Otherwise, could be done by iterating manually using `grow_evotree!(model, cache)`.

**Comment by Moelf** [comment]
actually, in the `XGBoost` case, you can just use the first N trees to make prediction, since there's no sense of "time" anyway.

In EvoTrees.jl it should be trivial to just use the first N estimators to predict/fit?
