### ISSUE TITLE
Probabilistic Forecast

### ISSUE THREAD

**Issue by 1991jhf** [Evovest/EvoTrees.jl#239]
Is there any plan to support probabilistic forecast? 
Similar project below:
https://github.com/stanfordmlgroup/ngboost
https://github.com/StatMixedML/XGBoostLSS
https://github.com/StatMixedML/LightGBMLSS

**Comment by jeremiedb** [comment]
The `EvoTreeMLE` constructor supports predicitons for both Gaussian and Logistic probabilistic distrbutions (predicitons returns the estimates for each of the 2 parameters of these distributions). Otherwise, there are the deviance maximum likelihood that is used for the `gamma` and `tweedie` losses (available losses with `EvoTreeRegressor`) and  `poisson` (used in `EvoTreeCount`). 

I didn't have any further probabilistic initiatives on the roadmap. For other probabilistic needs, you may want to consider https://github.com/JuliaTrustworthyAI/ConformalPrediction.jl, which already provides usage examples with EvoTrees. 

If there's a specific use case that isn't adressed, feel free to provide more details and about it.

**Comment by 1991jhf** [comment]
Thank you! EvoTreeMLE is exactly what I need.
