### ISSUE TITLE
Feature Request: Support Tables.jl

### ISSUE THREAD

**Issue by xiaodaigh** [Evovest/EvoTrees.jl#53]
Happy to contribute if there is a desire to support Tables.jl

**Comment by jeremiedb** [comment]
Thanks for the offer! 

As currently the whole internal machinery operates on Floats, I guess that a an naive way to first add support for Tables.jl would be by simply have an initial preprocessing that converts a Table into a Matrix. That would be similar to how the MLJ integration handles table through the Matrix conversion. 

Given that I'm looking forward a GPU support, which would naturally operates on Array of floats, my first reflex would be to keep the the internal mechanics of the library operates on such structure rather than a Tables with potentially diverses data types. 

Where you having some other thoughts in mind?

**Comment by jeremiedb** [comment]
At this moment, I think that Tables format is best handled through the integration with MLJ.
